config/routes.rb
Rails.application.routes.draw do
  # get 'admin/index'
  # get 'admin/update'

  devise_for :owners, :controllers => { :omniauth_callbacks => "owners/omniauth_callbacks" }
  get 'apartments/all_map_locations'

  # devise_scope :owner do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_owner_session
  # end

  resources :apartments do
    get 'map_location'
    get 'search', on: :collection
  end

  get "admin" => "admin#index"
  put "admin/:id" => "admin#update"
  patch "admin/:id" => "admin#update"

  root 'apartments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(owner)

    if owner.nil?
      owner = Owner.new
      # owner.add_role("poster")
    end

      if owner.has_role? :admin
        can :manage, :all
      elsif owner.has_role? :moderator
        can :manage, Apartment
      else owner.has_role? :poster
        can :manage, Apartment, owner_id: owner.id
      end

      # can :read, :all

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :owner
  geocoded_by :full_street_address
  after_validation :geocode

  resourcify

  def full_street_address
    street_1.to_s + ' ' + ', ' + city.to_s + ', ' + state.to_s + ', ' + country.to_s + ', ' + zip.to_s
  end

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, presence: true,
      content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
      size: { in: 0..10.megabytes }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  rolify
  after_create :assign_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]

  has_many :apartments

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |owner|
      owner.email = auth.uid + "@twitter.com"
      owner.password = Devise.friendly_token[0,20]
    end
  end

  def assign_role
    add_role(:poster)
  end


end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :owners, :join_table => :owners_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_owner!
  before_action :authorize

  def index
    @owners = Owner.all
  end

  def update
    owner = Owner.find(params[:id])
    owner.remove_role owner.roles.first.name # user only has one role
    new_role = params[:role]
    owner.add_role new_role
    redirect_to '/admin'
  end

  private
  def authorize
    if !current_owner.has_role? :admin
      render text:"No access for you!"
    end
  end

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!, except: [:show, :index, :all_map_locations, :map_location]
  load_and_authorize_resource

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  def all_map_locations
    if !params[:search].blank?
      apartments = Apartment.search(params[:search][:search_string])
    else
      apartments = Apartment.all
    end
    @hash = Gmaps4rails.build_markers(apartments) do |apartment, marker|
      marker.lat(apartment.latitude)
      marker.lng(apartment.longitude)
      marker.infowindow("<em>" + apartment.full_street_address + "</em>")
    end
    render json: @hash.to_json
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  def map_location
    @apartment = Apartment.find(params[:apartment_id])
    @hash = Gmaps4rails.build_markers(@apartment) do |apartment, marker|
      marker.lat(apartment.latitude)
      marker.lng(apartment.longitude)
      marker.infowindow("<em>" + apartment.full_street_address + "</em>")
    end
    render json: @hash.to_json
  end

  # GET /apartments/new
  def new
    @apartment = current_owner.apartments.build
  end

  # GET /apartments/1/edit
  def edit
  end

  def search
    @apartments = Apartment.search(params[:search])
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = current_owner.apartments.build(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:street_1, :street_2, :city, :zip, :state, :country, :name, :phone_number, :availability, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_ability
    @current_ability ||= Ability.new(current_owner)
  end
end

app/controllers/owners/omniauth_callbacks_controller.rb
class Owners::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    # You need to implement the method below in your model (e.g. app/models/owner.rb)
    @owner = Owner.from_omniauth(request.env["omniauth.auth"])

    if @owner.persisted?
      sign_in_and_redirect @owner, :event => :authentication #this will throw if @owner is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_owner_registration_url
    end
  end

  def failure
    redirect_to root_path
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Owners</h1>
<table>
  <thead>
    <thead>
      <tr>
        <th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @owners.each do |owner| %>
    <tr>
      <td><%= owner.email %></td>
      <td><%= owner.roles.first.name %></td>
      <td>
        <%= form_tag("/admin/" + owner.id.to_s + "?role=poster", method: :PUT) do %>
          <input type="submit" value="Make Poster"/>
        <% end %>
      </td>
      <td>
        <%= form_tag("/admin/" + owner.id.to_s + "?role=moderator", method: :PUT) do %>
          <input type="submit" value="Make Moderator"/>
        <% end %>
      </td>
      <td>
        <%= form_tag("/admin/" + owner.id.to_s + "?role=admin", method: :PUT) do %>
          <input type="submit" value="Make Admin"/>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/apartments/_form.html.erb
<%= form_for(apartment, html: { multipart: true}) do |f| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_1 %>
    <%= f.text_field :street_1 %>
  </div>

  <div class="field">
    <%= f.label :street_2 %>
    <%= f.text_field :street_2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :availability %>
    <%= f.text_field :availability %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Apartments</h1>
<hr>
<!-- Search form -->
<form action="/apartments/search" method="get" id="search_form">
  <label for="search">Search</label>
  <input type="text" name="search" id="search_box" />
  <input type="submit" value="Search" class="button">
</form>

<!-- New Apartment button (only for logged in users(called owners)) -->
<% if(!current_owner.nil?)%>
  <%= button_to 'New Apartment', new_apartment_path, id: 'new_apartment_link', class: 'button', method: :get %>
<%end%>

<!-- Listing of all Apartments -->
<table id="index_table">
  <thead>
    <tr>
      <th>Street 1</th>
      <th>Street 2</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zip</th>
      <th>Name</th>
      <th>Phone Number</th>
      <th>Availability</th>
      <th>Preview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.street_1 %></td>
        <td><%= apartment.street_2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.zip %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.phone_number %></td>
        <td><%= apartment.availability %></td>
        <td><%= link_to image_tag(apartment.image.url(:small)), apartment.image.url %></td>
        <td><%= button_to 'Show', apartment_path(apartment), class: 'button', method: :get %></td>
        <!-- Only the owner of the apartment or a moderator or admin can edit/delete apartments -->
        <% if !current_owner.nil? && ((apartment.owner == current_owner && current_owner.has_role?("poster")) || current_owner.has_role?("moderator") || current_owner.has_role?("admin")) %>
        <td><%= button_to 'Edit', edit_apartment_path(apartment), class: 'button', method: :get %></td>
        <td><%= button_to 'Destroy', apartment_path(apartment), class: 'button', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- Google Map! -->
<div id="all_apartments_map">Google Map will appear here...</div>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/search.html.erb
<!-- Same table as index page but populated only by search results -->
<table>
  <thead>
    <tr>
      <th>Street 1</th>
      <th>Street 2</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zip</th>
      <th>Name</th>
      <th>Phone Number</th>
      <th>Availability</th>
      <th>Preview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.street_1 %></td>
        <td><%= apartment.street_2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.zip %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.phone_number %></td>
        <td><%= apartment.availability %></td>
        <td><%= link_to image_tag(apartment.image.url(:small)), apartment.image.url %></td>
        <td><%= link_to 'Show', apartment %></td>
        <% if !current_owner.nil? && ((apartment.owner == current_owner && current_owner.has_role?("poster")) || current_owner.has_role?("moderator") || current_owner.has_role?("admin")) %>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="all_apartments_map" data-search-string="<%= params[:search] %>">Google Map will appear here...</div>

app/views/apartments/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Street 1:</strong>
  <%= @apartment.street_1 %>
</p>

<p>
  <strong>Street 2:</strong>
  <%= @apartment.street_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @apartment.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @apartment.phone_number %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @apartment.availability %>
</p>

<p>
  <strong>Image:</strong>
  <%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>
</p>

<% if !current_owner.nil? && ((@apartment.owner == current_owner && current_owner.has_role?("poster")) || current_owner.has_role?("moderator") || current_owner.has_role?("admin")) %>
  <%= link_to 'Edit', edit_apartment_path(@apartment) %> |
  <%= link_to 'Destroy', apartment_path(@apartment), method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', apartments_path %>

<hr>

<!-- Shows both your own location AND the apartment's location -->
<div id="apartment_map" data-apartment-id="<%=@apartment.id%>">Google Map will appear here...</div>

app/views/layouts/_header.html.erb
<%= link_to 'Home', apartments_path %> |

<% if current_owner.nil? %>
<%= link_to 'Register', new_owner_registration_path %> |
<%= link_to 'Sign In', new_owner_session_path %> |
<%= link_to "Sign in with Twitter", owner_twitter_omniauth_authorize_path %>
<% end %>

<% if !current_owner.nil? %>

  <%= link_to 'Sign Out', destroy_owner_session_path, method: 'delete' %>

  <% current_owner.roles.each do |role| %> |
    <%= role.name %>
  <%end%>

<% end %>


<% if !current_owner.nil? && current_owner.has_role?("admin") %>
  | <%= link_to "Admin Page", admin_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeolocatorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCioMZ6dc5oXrFK51xOhtG5DRJVxHZO-As"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>

  </head>

  <body>

    <%= render '/layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>